version: '3.9'

services:
  api:
    image: tyskerdocker/datamatiker:1.0.1
    container_name: app
    environment:
        CONNECTION_STR: ${CONNECTION_STR}
        DB_USERNAME: ${DB_PASSWORD}
        DB_PASSWORD: ${DB_PASSWORD}
        DEPLOYED: ${DEPLOYED}
        SECRET_KEY: ${SECRET_KEY}
        TOKEN_EXPIRE_TIME: 1800000
        ISSUER: ${ISSUER}
    ports:
      - "7070:7070"
    networks:
      - database_network

networks:
  database_network:
    name: database_network
    internal: false
    driver: bridge